name: papertrader

services:
  backend:
    build: 
      context: ./
      dockerfile: backend.Dockerfile
    ports:
    - "8000:8001"

  frontend:
    build: 
      context: ./
      dockerfile: frontend.Dockerfile
    ports:
    - "3000:3001"
    links:
    - backend