# Generated by Django 5.0.4 on 2024-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('transaction_type', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
